# Generated by Django 4.1.2 on 2022-10-18 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreEmpresa', models.CharField(default='', max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('rubro', models.CharField(default='', max_length=255)),
                ('tamanio', models.IntegerField(default=0)),
                ('mutualidad', models.CharField(default='', max_length=255)),
                ('numeroTelefono', models.CharField(default='', max_length=20)),
                ('contrasena', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('categoria', models.CharField(default='', max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(default='18/10/2022', max_length=10)),
                ('observaciones', models.CharField(max_length=255)),
                ('recomendaciones', models.CharField(default='', max_length=255)),
                ('rutCliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.cliente')),
                ('rutProfesional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montoPlan', models.IntegerField(default=0)),
                ('cantidadVisitas', models.IntegerField(default=0)),
                ('cantidadAsesorias', models.IntegerField(default=0)),
                ('cantidadCapacitaciones', models.IntegerField(default=0)),
                ('rutCliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montoPagado', models.IntegerField()),
                ('rutCliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Chequeo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idVisita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.visita')),
                ('rutCliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.cliente')),
                ('rutProfesional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(default='18/10/2022', max_length=10)),
                ('cantidadAsistentes', models.IntegerField()),
                ('motivo', models.CharField(max_length=255)),
                ('rutCliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.cliente')),
                ('rutProfesional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('rutCliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.cliente')),
                ('rutProfesional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.profesional')),
            ],
        ),
    ]
